### ISSUE TITLE
0.1.6 fail on build

### ISSUE THREAD

**Issue by sebastianvarela** [Label305/AutoRebase#51]
The 0.1 works perfectly, but the 0.1.6 fails with this error:
```
Run Label305/AutoRebase@0.1.6
  with:
    github_token: ***
Error: File not found: '/home/runner/work/_actions/Label305/AutoRebase/0.1.6/dist/index.js'
```

This is my configuration:
YML:
```YML
name: "auto-rebase"
on: 
  push:
    branches-ignore:
      # Ignore branches automatically created by github-rebase
      - rebase-pull-request**
      - cherry-pick-rebase-pull-request**  
  pull_request:
    types: [labeled]

jobs:
  build:
    name: Auto Rebase
    runs-on: ubuntu-latest
    steps:

    - name: Automatic Rebase
      uses: Label305/AutoRebase@v0.1.6
      with:
        github_token: ${{ secrets.THORBOT_GITHUB_API_TOKEN }}
```
